### ISSUE TITLE
No update of output_voltage, all other sensors are working

### ISSUE THREAD

**Issue by fmeili1** [mjpalmowski/CAN-BUS-control-R4875G1-with-ESPHome-and-MQTT#6]
I've successfully made the first tests with just one of my four R4875G1 sitting on my desk (no battery connected yet on the battery clamps, just a voltmeter for testing - no current/amp testing so far).

The web-view (webserver) and MQTT are working. I can control ON/OFF, voltage setting and fallback voltage setting, fan speed etc. The sensors showing correct values and updates for frequency, grid input voltage, temperature.

But the output voltage is NOT updating the output sensor. It looks like the unit does not send the 0x75 (Output Voltage) on 0x1081407F for the device. If I change the online output voltage to a new value (e.g. from 51V to 52V) the voltmeter showing 52V about a second later, but the output sensor still showing the old value (51V) and will never update, regardless how many changes are made on the output voltage. The old value sticks even after off/on (hibernate/on) and also after AC-power switching off/on.

The only way to get the actual correct sensor value (just once) for the output voltage is to install the YAML code again but it will never update again.

I've added an log printout in the 0x75 case but it will never triggered so I assume that the unit never sends out the output voltage via CAN. Beside requesting the values via broadcast (0x108040FE) I've also tried it with the unit 1 address (0x108140FE), but no change in the behavior.

Is it possible that the missing "consumer" (battery) on the output connectors for my test setup could result in such a problem (maybe the rectifier detects that there is no load [external battery] and even if the voltage is present it doesn't update the value)?

**Comment by mjpalmowski** [comment]
The web_server takes a lot of processing and might clash with the MQTT message servce or vice versa, try first to only activate the webserver compoent OR the  MQTT component, not both.

**Comment by fmeili1** [comment]
I've made a couple of tests and you're right. If both MQTT and webserver are active (I never use API) the output_voltage sensor will nearly never update (I see only once an update after >10 minutes wait time).

If I only have either MQTT or webserver activated, I see updates on the sensor - but it still takes between 10-45 seconds after the voltage changed on the output (voltmeter), before the sensor showing the update.
I don't really understand why nearly all other sensors get updates every couple of seconds (even if no change in the value - I've checked that with MQTT active where I can monitor the messages). It looks like only the output_voltage sensor is targeted by this problem.

Changing the output_voltage has no delay independent if both MQTT and webserver are running in parallel or not. About 1 seconds after changing the output voltage, the voltmeter showing the new value on the output connectors - only the sensor is stuck at the old value.

**Comment by mjpalmowski** [comment]
please attach the YAML that you are using and I will have a look if I can find the issue, should be much faster.

**Comment by fmeili1** [comment]
I found the problem. It was the massive amount of logging. After playing around with loglevel and deactivated the console logging (by setting: baud_rate: 0) everything works. With loglevel NONE I'm able to use both MQTT and webserver in parallel without delays for the output_voltage sensor.

Thanks for your help!

**Comment by mjpalmowski** [comment]
Well spotted! I should have thought of this too. If you remove the log entries from the rapid fire areas you can achieve big performance gains. Then set the log level to INFO or ERROR 
or as you already did, go radical and switch logs off ;)
